#!/usr/bin/zsh
#Changing to configs git dir.
cd ~/Myrcs
git status | grep "nothing to commit"
if [ $? -gt 0 ] # checking grep's exit status(previous command)
then
    sleep 2
    git add .
    git commit -m "Auto commit"
    git push
fi
