[env]
# TERM = "xterm-256color"
TERM = "alacritty"

[window]
opacity = 0.9
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

[general]
import = [
    "~/.config/alacritty/coolnight.toml"
]

